package com.voyagerproject.model;
// Generated Feb 27, 2016 12:34:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BugSystemType generated by hbm2java
 */
@Entity
@Table(name = "bugsystemtype", catalog = "Voyager")
public class BugSystemType extends Type implements java.io.Serializable {

	private static final long serialVersionUID = 2908259411074500774L;
	private Date createdOn;

	public BugSystemType() {
	}

	public BugSystemType(int id, String name, Date createdOn) {
		this.setId(id);
		this.setName(name);
		this.createdOn = createdOn;
	}
	
	public BugSystemType(String name, Date createdOn) {
		this.setName(name);
		this.createdOn = createdOn;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idBugSystemType", unique = true, nullable = false)
	public int getIdBugSystemType() {
		return this.getId();
	}

	public void setIdBugSystemType(int id) {
		this.setId(id);;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return super.getName();
	}

	public void setName(String name) {
		super.setName(name);
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 19, insertable = false)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
