package com.voyagerproject.model;
// Generated Feb 27, 2016 12:34:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "Voyager")
public class Project implements java.io.Serializable {

	private static final long serialVersionUID = -3196981065072616409L;
	private int idProject;
	private String name;
	private BugSystem bugSystem;
	private RuleManager ruleManager;
	private Date createdOn;

	public Project() {
	}
	
	public Project(int idProject, String name, BugSystem bugSystem, RuleManager ruleManager, Date createdOn) {
		this.idProject = idProject;
		this.name = name;
		this.bugSystem = bugSystem;
		this.ruleManager = ruleManager;
		this.createdOn = createdOn;
	}
	
	public Project(String name, BugSystem bugSystem, RuleManager ruleManager, Date createdOn) {
		this.name = name;
		this.bugSystem = bugSystem;
		this.ruleManager = ruleManager;
		this.createdOn = createdOn;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idProject", unique = true, nullable = false)
	public int getIdProject() {
		return this.idProject;
	}

	public void setIdProject(int idProject) {
		this.idProject = idProject;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@OneToOne
    @JoinColumn(name = "bugSystem", nullable = false)
	public BugSystem getBugSystem() {
		return this.bugSystem;
	}

	public void setBugSystem(BugSystem bugSystem) {
		this.bugSystem = bugSystem;
	}

	@OneToOne
    @JoinColumn(name = "ruleManager")
	public RuleManager getRuleManager() {
		return this.ruleManager;
	}

	public void setRuleManager(RuleManager ruleManager) {
		this.ruleManager = ruleManager;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 19, insertable = false)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}
}
