package com.voyagerproject.model;
// Generated Feb 28, 2016 12:50:47 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "usertype", catalog = "Voyager")
public class UserType implements java.io.Serializable {

	private static final long serialVersionUID = 8879097156881624765L;
	private int idUserType;
	private String name;
	private Date createdOn;

	public UserType() {
	}

	public UserType(int idUserType, String name, Date createdOn) {
		this.idUserType = idUserType;
		this.name = name;
		this.createdOn = createdOn;
	}
	
	public UserType(String name, Date createdOn) {
		this.name = name;
		this.createdOn = createdOn;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idUserType", unique = true, nullable = false)
	public int getIdUserType() {
		return this.idUserType;
	}

	public void setIdUserType(int idUserType) {
		this.idUserType = idUserType;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 19, insertable = false)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
